/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TrustFundInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProject"
      | "fundProject"
      | "nextProjectId"
      | "projects"
      | "releaseMilestone"
      | "requestMilestone"
      | "voteMilestone"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MilestonePayout"
      | "MilestoneRequested"
      | "ProjectCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createProject",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fundProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextProjectId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteMilestone",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextProjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteMilestone",
    data: BytesLike
  ): Result;
}

export namespace MilestonePayoutEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    milestoneId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    milestoneId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    milestoneId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneRequestedEvent {
  export type InputTuple = [projectId: BigNumberish, milestoneId: BigNumberish];
  export type OutputTuple = [projectId: bigint, milestoneId: bigint];
  export interface OutputObject {
    projectId: bigint;
    milestoneId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [projectId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [projectId: bigint, creator: string];
  export interface OutputObject {
    projectId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustFund extends BaseContract {
  connect(runner?: ContractRunner | null): TrustFund;
  waitForDeployment(): Promise<this>;

  interface: TrustFundInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProject: TypedContractMethod<
    [titles: string[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  fundProject: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "payable"
  >;

  nextProjectId: TypedContractMethod<[], [bigint], "view">;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        owner: string;
        totalFunding: bigint;
        milestoneCount: bigint;
        funderCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  releaseMilestone: TypedContractMethod<
    [projectId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestMilestone: TypedContractMethod<
    [projectId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  voteMilestone: TypedContractMethod<
    [projectId: BigNumberish, milestoneId: BigNumberish, approve: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [titles: string[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundProject"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "nextProjectId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        owner: string;
        totalFunding: bigint;
        milestoneCount: bigint;
        funderCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<
    [projectId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestMilestone"
  ): TypedContractMethod<
    [projectId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteMilestone"
  ): TypedContractMethod<
    [projectId: BigNumberish, milestoneId: BigNumberish, approve: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MilestonePayout"
  ): TypedContractEvent<
    MilestonePayoutEvent.InputTuple,
    MilestonePayoutEvent.OutputTuple,
    MilestonePayoutEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneRequested"
  ): TypedContractEvent<
    MilestoneRequestedEvent.InputTuple,
    MilestoneRequestedEvent.OutputTuple,
    MilestoneRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;

  filters: {
    "MilestonePayout(uint256,uint256,uint256)": TypedContractEvent<
      MilestonePayoutEvent.InputTuple,
      MilestonePayoutEvent.OutputTuple,
      MilestonePayoutEvent.OutputObject
    >;
    MilestonePayout: TypedContractEvent<
      MilestonePayoutEvent.InputTuple,
      MilestonePayoutEvent.OutputTuple,
      MilestonePayoutEvent.OutputObject
    >;

    "MilestoneRequested(uint256,uint256)": TypedContractEvent<
      MilestoneRequestedEvent.InputTuple,
      MilestoneRequestedEvent.OutputTuple,
      MilestoneRequestedEvent.OutputObject
    >;
    MilestoneRequested: TypedContractEvent<
      MilestoneRequestedEvent.InputTuple,
      MilestoneRequestedEvent.OutputTuple,
      MilestoneRequestedEvent.OutputObject
    >;

    "ProjectCreated(uint256,address)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
  };
}
